name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_HOST: 'localhost'
          MYSQL_DATABASE: github_acttion_rails_test
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_SOCKET: /tmp/mysql.
    container:
      image: ruby:2.6.5
      env:
        MYSQL_HOST: 'localhost'
        MYSQL_DATABASE: github_acttion_rails_test
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_SOCKET: /tmp/mysql.
    steps:
    - uses: actions/checkout@v2

    - name: Build
      env:
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle install --jobs 4
        bin/rails db:create RAILS_ENV=test

    - name: Run test
      run: |
        bin/rails test
